version: '3'

networks:
  internal:

volumes:
  db-data:
  concierge-data:

services:
  mysql:
    image: mysql:8.0
    container_name: concierge-db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  concierge:
    build:
      context: .
    image: razorpay/concierge:v2
    container_name: concierge-ingress
    networks:
      - internal
    volumes:
      - concierge-data:/app
      - ~/.kube/config:/root/.kube/config
      - ./oauth2_proxy/oauth2_proxy.cfg:/app/oauth2_proxy/oauth2_proxy.cfg
    ports:
      - 4180:4180
      - 8190:8190
    command: start
    env_file: .env
    depends_on:
      - mysql
    restart: always
